services:
  - type: web
    name: coach-route-system
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://coach_route_system_user:8R2RINx2Bl17evSPcR8j5gJkGVfdeNsR@dpg-cuplagdsvqrc73f31cbg-a.oregon-postgres.render.com/coach_route_system"
    plan: starter
